### ISSUE TITLE
load styles and scripts on index pages if posts contain slider

### ISSUE THREAD

**Issue by teresacamachohull** [jekylltools/jekyll-ideal-image-slider-include#6]
here it works:
https://teresacamachohull.github.io/2016/09/19/This-thursday/ 

but here it doesn't:
https://teresacamachohull.github.io/

when i look at view source for the post page, i can see the image slider's css and js loaded, but i can't see any of them loaded when i look at the source image for the home page.
any ideas?  

thank you!

**Comment by teresacamachohull** [comment]
never mind, figured it out. ;) thanks.

**Comment by jekylltools** [comment]
Ah, you found a bug! I need to make a way to load the slider styles and scripts on index pages if any of the posts appearing on an index contain a gallery.

**Comment by jekylltools** [comment]
@teresacamachohull for example this page on your site is not displaying sliders correctly: https://teresacamachohull.github.io/page2/

**Comment by jekylltools** [comment]
fixed in 1.4 (https://github.com/jekylltools/jekyll-ideal-image-slider-include/commit/15d284672540403a8d932b9df49269d3982549fe) thanks for bringing this to my attention!
