### ISSUE TITLE
Support bullet navigation extension

### ISSUE THREAD

**Issue by ICTime** [jekylltools/jekyll-ideal-image-slider-include#7]
I am so lucky finding this feature.  It is simple and straight. 

There is two feature request: 

Adding slide navigation, so that we can click to switch to one picture 

Control the text format , Make it larger 

Live example:  https://www.twosigma.com/

**Comment by jekylltools** [comment]
Sure, I can add bullet navigation. Ideal Image Slider has a [bullet navigation extension](http://idealimageslider.com/demo/bullet-nav.html) so I'll support it in the code.

If you want to control the text format you can style the text in the captions. You can style `iis-caption`, `iis-caption-title` and `iis-caption-content` to alter the size and font styles.

**Comment by ICTime** [comment]
I found that CCS too, Thanks alot
And is that possible making the TEXT (title  and alt) had some motion feature ?

**Comment by jekylltools** [comment]
What type of motion feature would you like to add?

**Comment by ICTime** [comment]
the simplest motion,  like https://twosigma.com/  (home page slide) 

following your advice in Issue #8,  I clone minima, and adding your slide include files,  it works good. 
Thanks very much

**Comment by jekylltools** [comment]
The [Ideal Image Slider](http://idealimageslider.com) doesn't support that sort of motion, you would need to add it yourself.

**Comment by jekylltools** [comment]
added bullet nav support in v1.5
